/* ────────────────────────────────────────────────────────────────────────────
   VOICE LAYER — injected into the unmodified Adventures With Anxiety build.

   It does not rewrite the game. It watches the game's own DOM:
     #game_words    the current dialogue line   -> speak it in the character's voice
     #game_choices  the current choices         -> read them in the META voice, then listen
   and clicks a real choice element when speech matches one. All art, animation,
   sound and layout keep working because nothing in the game is touched.

   Four distinct voices:
     hong / beebee  in-fiction characters
     narrator       the ALL-CAPS battle announcer (in-fiction)
     meta           the assistant reading options and asking you to choose

   Requires voice-index.js (generated by tools/parse.mjs) loaded before this.
   ──────────────────────────────────────────────────────────────────────────── */
(function () {
  "use strict";

  const CFG = {
    words:   "#game_words",
    choices: "#game_choices",
    settleMs: 80,       // DOM mutations are batched; the full hidden text already exists
    choiceSettleMs: 120,
    micDelayMs: 260,    // gap after the meta voice finishes before the mic opens
    autoMic: true,
    readOptions: true,
    syncAdvance: true,  // keep the game click-driven and advance after voice playback
    preloadAudio: true,
  };

  const locale = window.GAME_LOCALE || new URLSearchParams(window.location.search).get("lang") || "en-US";
  const language = locale.toLowerCase().split("-")[0];

  const log = [];
  let muted = false, voiceRateMultiplier = 1;

  /* ── voices ───────────────────────────────────────────────────────────── */
  const synth = window.speechSynthesis;
  let voices = [];
  function loadVoices() {
    const all = synth ? synth.getVoices() : [];
    const localized = all.filter((v) => v.lang && v.lang.toLowerCase().startsWith(language));
    const en = all.filter((v) => /^en/i.test(v.lang));
    voices = localized.length ? localized : (en.length ? en : all);
  }
  if (synth) { loadVoices(); synth.addEventListener("voiceschanged", loadVoices); }

  // Keep most voices near their natural pitch for intelligibility. Beebee is
  // intentionally the one stylized, low-pitched anxiety-wolf voice.
  const VOICE = {
    hong:     { slot: 0, pitch: 1.05, rate: 0.96, prefer: ["Samantha", "Ava", "Allison", "Karen"] },
    beebee:   { slot: 1, pitch: 0.70, rate: 1.16 },
    narrator: { slot: 2, pitch: 0.90, rate: 0.92, prefer: ["Alex", "Daniel"] },
    meta:     { slot: 3, pitch: 1.05, rate: 0.94, prefer: ["Samantha", "Ava", "Karen"] },
    al:       { slot: 4, pitch: 0.98, rate: 0.96 },
    shire:    { slot: 5, pitch: 1.06, rate: 0.96 },
    hunter:   { slot: 6, pitch: 0.92, rate: 0.94 },
  };

  function voiceFor(cfg) {
    const preferred = cfg.prefer || [];
    for (const name of preferred) {
      const found = voices.find((voice) => voice.name.toLowerCase().includes(name.toLowerCase()));
      if (found) return found;
    }
    return voices.length ? voices[cfg.slot % voices.length] : null;
  }

  const audioCache = new Map();
  let activeAudio = null, activeAudioResolve = null, playbackSeq = 0;

  function playRecorded(line, seq) {
    return new Promise((resolve) => {
      const manifestLine = line && window.VOICE_AUDIO_MANIFEST && window.VOICE_AUDIO_MANIFEST.lines
        ? window.VOICE_AUDIO_MANIFEST.lines[line.id] : null;
      if (!manifestLine || !manifestLine.available || !manifestLine.file) return resolve(false);
      let audio = audioCache.get(line.id);
      if (!audio) { audio = new Audio(manifestLine.file); audio.preload = "auto"; audioCache.set(line.id, audio); }
      activeAudio = audio;
      activeAudioResolve = resolve;
      audio.currentTime = 0;
      audio.onended = () => { activeAudio = null; activeAudioResolve = null; resolve(seq === playbackSeq); };
      audio.onerror = () => { activeAudio = null; activeAudioResolve = null; resolve(false); };
      const started = audio.play();
      if (started && typeof started.catch === "function") started.catch(() => resolve(false));
    });
  }

  async function speak(text, who, line) {
    const seq = ++playbackSeq;
    if (muted || !text) return false;
    if (await playRecorded(line, seq)) return true;
    return new Promise((resolve) => {
      if (!synth || seq !== playbackSeq) return resolve(false);
      const cfg = VOICE[who] || VOICE.meta;
      const u = new SpeechSynthesisUtterance(text);
      u.lang = locale;
      const selectedVoice = voiceFor(cfg);
      if (selectedVoice) u.voice = selectedVoice;
      u.pitch = cfg.pitch;
      u.rate = Math.max(0.65, Math.min(1.5, cfg.rate * voiceRateMultiplier));
      let done = false;
      const fin = () => { if (!done) { done = true; resolve(seq === playbackSeq); } };
      u.onend = fin; u.onerror = fin;
      setTimeout(fin, 700 + text.length * 95);   // safety net
      synth.speak(u);
    });
  }
  const shutUp = () => {
    playbackSeq++;
    if (activeAudio) { try { activeAudio.pause(); } catch (e) {} activeAudio = null; }
    if (activeAudioResolve) { activeAudioResolve(false); activeAudioResolve = null; }
    try { synth && synth.cancel(); } catch (e) {}
  };

  function preloadAudio() {
    if (!CFG.preloadAudio || !window.VOICE_AUDIO_MANIFEST) return;
    Object.values(window.VOICE_AUDIO_MANIFEST.lines || {}).filter((line) => line.available).forEach((line) => {
      const audio = new Audio(line.file); audio.preload = "auto"; audio.load(); audioCache.set(line.id, audio);
    });
  }

  /* ── who is speaking ──────────────────────────────────────────────────── */
  const keyOf = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, "");
  function lineFor(text, speakerHint) {
    const idx = window.VOICE_INDEX || {};
    const k = keyOf(text);
    if (idx.version === 2) {
      const ids = idx.byText[k] || [];
      return ids.map((id) => idx.lines[id]).find((line) => !speakerHint || line.speaker === speakerHint)
        || (ids[0] ? idx.lines[ids[0]] : null);
    }
    return idx[k] ? { speaker: idx[k], text } : null;
  }
  function speakerHintFor(el) {
    const cls = el && el.className || "";
    if (/beebee-bubble/.test(cls)) return "beebee";
    if (/hong/.test(cls)) return "hong";
    if (/al-bubble/.test(cls)) return "al";
    if (/shire-bubble/.test(cls)) return "shire";
    if (/hunter-bubble/.test(cls)) return "hunter";
    if (/narrator/.test(cls)) return "narrator";
    return null;
  }
  function speakerFor(text, bubble) {
    const hint = speakerHintFor(bubble);
    const line = lineFor(text, hint);
    return line ? line.speaker : (hint || (/^[^a-z]*$/.test(text) ? "narrator" : "hong"));
  }

  /* ── matcher (single canonical implementation in matcher.js) ─────────── */
  if (!window.Matcher || typeof window.Matcher.match !== "function") {
    throw new Error("voice-layer.js requires matcher.js to be loaded first");
  }
  const match = (alts, texts) => window.Matcher.match(alts, texts.map((text) => ({ text })));

  /* ── reading the game ─────────────────────────────────────────────────── */
  const $ = (s) => document.querySelector(s);
  const textOf = (el) => (el ? (el.innerText || el.textContent || "").replace(/\s+/g, " ").trim() : "");

  const ICON_CHOICE_LABELS = {
    fear_harm: "Harm attack",
    fear_alone: "Loneliness attack",
    fear_bad: "Bad person attack",
  };

  function choiceTextOf(el) {
    if (el && el._voiceLabel) return el._voiceLabel;
    const text = textOf(el);
    if (text) return text;
    if (!el) return "";
    if (el.id === "options_ok") return "Okay";
    return ICON_CHOICE_LABELS[el.getAttribute("speaker")] || el.getAttribute("aria-label") || el.title || "";
  }

  function virtualControl(label, action) {
    return {
      _voiceLabel: label,
      onclick: action,
      click: () => {
        action();
        choiceKey = "";
        setTimeout(onChoicesChanged, 450);
      },
    };
  }

  function adjustTextSpeed(delta) {
    const slider = $("#text_speed_slider");
    if (!slider) return;
    slider.value = Math.max(Number(slider.min), Math.min(Number(slider.max), Number(slider.value) + delta));
    slider.dispatchEvent(new Event("input", { bubbles: true }));
    hudStatus(delta > 0 ? "Text speed increased" : "Text speed decreased");
  }

  function adjustVoiceSpeed(delta) {
    voiceRateMultiplier = Math.max(0.75, Math.min(1.3, voiceRateMultiplier + delta));
    hudStatus("Voice speed " + Math.round(voiceRateMultiplier * 100) + "%");
  }

  function optionsControlEls() {
    const panel = $("#options"), okay = $("#options_ok");
    if (!panel || !panel.style.top || !okay) return [];
    return [
      virtualControl("Faster voice", () => adjustVoiceSpeed(0.1)),
      virtualControl("Slower voice", () => adjustVoiceSpeed(-0.1)),
      virtualControl("Faster text", () => adjustTextSpeed(0.12)),
      virtualControl("Slower text", () => adjustTextSpeed(-0.12)),
      okay,
    ];
  }

  function choiceEls() {
    const controls = optionsControlEls();
    if (controls.length) return controls;
    const root = $(CFG.choices);
    if (!root) return [];
    const els = Array.prototype.slice.call(root.children);
    return els.filter((el) => typeof el.onclick === "function" && choiceTextOf(el).length > 0);
  }

  function clickIt(el) {
    // HTMLElement.click() already emits the authored click once. Dispatching a
    // synthetic click as well can execute the branch twice.
    if (el && typeof el.click === "function") el.click();
  }

  /* ── speaking dialogue as it appears ──────────────────────────────────── */
  let lastBubble = null, settleTimer = null;

  function latestBubble() {
    const root = $(CFG.words);
    if (!root) return null;
    const children = Array.prototype.slice.call(root.children);
    for (let i = children.length - 1; i >= 0; i--) if (textOf(children[i])) return children[i];
    return null;
  }

  function advanceAfterSpeech(bubble) {
    if (!CFG.syncAdvance || bubble !== latestBubble() || choiceEls().length) return;
    if (!window.Game || typeof window.Game.clearAllTimeouts !== "function") return;
    const wasStillTyping = window.Game.WHO_IS_SPEAKING != null;
    window.Game.clearAllTimeouts();
    // In this game the first click while typing reveals the full line, and the
    // second advances. Do both synchronously so the next line cannot be skipped.
    if (wasStillTyping) window.Game.clearAllTimeouts();
  }

  function onWordsChanged() {
    clearTimeout(settleTimer);
    settleTimer = setTimeout(() => {
      const bubble = latestBubble();
      const t = textOf(bubble);
      if (!t || bubble === lastBubble) return;
      lastBubble = bubble;
      shutUp();
      const who = speakerFor(t, bubble);
      const line = lineFor(t, who);
      hudStatus(who + ": " + t.slice(0, 60));
      speak(t, who, line).then((completed) => { if (completed) advanceAfterSpeech(bubble); });
    }, CFG.settleMs);
  }

  /* ── choices: meta voice reads them, then the mic opens ───────────────── */
  let choiceKey = "", choiceEpoch = 0, choiceTimer = null;

  function onChoicesChanged() {
    const epoch = ++choiceEpoch;
    clearTimeout(choiceTimer);
    choiceTimer = setTimeout(() => processChoices(epoch), CFG.choiceSettleMs);
  }

  async function processChoices(epoch) {
    const els = choiceEls();
    if (!els.length) { choiceKey = ""; stopMic(); return; }

    const texts = els.map(choiceTextOf);
    const key = texts.join("|");
    if (key === choiceKey) return;
    choiceKey = key;

    if (CFG.readOptions) {
      shutUp();
      const words = language === "hi" ? ["एक", "दो", "तीन", "चार", "पाँच"] : ["one", "two", "three", "four", "five"];
      await speak(language === "hi" ? "आपके विकल्प हैं।" : "Your options are.", "meta");
      if (epoch !== choiceEpoch) return;
      for (let i = 0; i < texts.length; i++) {
        await speak((language === "hi" ? "विकल्प " : "Option ") + (words[i] || i + 1) + ". " + texts[i], "meta");
        if (epoch !== choiceEpoch) return;
      }
      await speak(language === "hi" ? "आप क्या चुनना चाहेंगे?" : "Which one do you choose?", "meta");
      if (epoch !== choiceEpoch) return;
    }

    if (choiceKey !== key || key !== choiceEls().map(choiceTextOf).join("|")) return;
    if (CFG.autoMic) setTimeout(() => startMic(texts, els, key), CFG.micDelayMs);
    else hudStatus("Press M to speak");
  }

  /* ── speech input + latency measurement ───────────────────────────────── */
  const externalSTT = window.VocalBridgeSTT;
  let retryPending = null, externalListening = false;
  let micPermission = "unknown", micPermissionPromise = null;

  async function primeMicPermission() {
    if (micPermission === "granted") return true;
    if (micPermissionPromise) return micPermissionPromise;
    if (!externalSTT) {
      micPermission = "unavailable";
      hudStatus("Vocal Bridge STT bundle is unavailable");
      return false;
    }
    hudStatus("Connecting Vocal Bridge speech recognition...");
    micPermissionPromise = externalSTT.prime((status) => hudStatus(status)).then(() => {
      micPermission = "granted";
      hudStatus("Vocal Bridge STT ready - voice layer enabled");
      return true;
    }).catch((error) => {
      micPermission = "error";
      hudStatus("Vocal Bridge unavailable: " + (error?.message || error?.code || "connection failed"));
      return false;
    }).finally(() => { micPermissionPromise = null; });
    return micPermissionPromise;
  }

  async function enableMicAndStart(texts, els, key) {
    if (await primeMicPermission()) startMic(texts, els, key);
  }

  function stopMic() {
    retryPending = null;
    if (externalSTT && externalListening) externalSTT.stop().catch(() => {});
    externalListening = false;
    hudLive(false);
  }

  function retryMic(texts, els, key) {
    retryPending = { texts, els, key };
    setTimeout(() => {
      const retry = retryPending; retryPending = null;
      if (retry && choiceKey === retry.key) startMic(retry.texts, retry.els, retry.key);
    }, 400);
  }

  function handleFinalTranscript(heard, alts, texts, els, key, sttMs, provider, speechEndAt) {
    const mStart = performance.now();
    const m = match(alts, texts);
    const matchMs = Math.round(performance.now() - mStart);
    if (m.confident && choiceKey === key) {
      const total = Math.round(performance.now() - speechEndAt);
      record(heard, texts[m.index], m, sttMs, matchMs, total, provider);
      hudStatus("OK via " + provider + ": " + texts[m.index], false);
      shutUp();
      clickIt(els[m.index]);
    } else if (m.index >= 0) {
      record(heard, texts[m.index] + " (unsure)", m, sttMs, matchMs, null, provider);
      hudStatus('unsure - say it again, or say "option ' + (m.index + 1) + '"');
      retryMic(texts, els, key);
    } else {
      record(heard, null, m, sttMs, matchMs, null, provider);
      hudStatus('no match - try "option 1"');
      retryMic(texts, els, key);
    }
  }

  function startMic(texts, els, key) {
    if (micPermission !== "granted") return hudStatus("Tap the mic button to enable microphone access");
    if (!externalSTT) return hudStatus("Vocal Bridge STT is not loaded");
    return startExternalMic(texts, els, key);
  }

  async function startExternalMic(texts, els, key) {
    if (externalListening) return;
    externalListening = true;
    const listenStarted = performance.now();
    let lastInterimAt = listenStarted;
    try {
      const started = await externalSTT.listen({
        onStatus: (status) => hudStatus(status),
        onStart: () => hudStatus("listening via Vocal Bridge...", true),
        onInterim: (heard) => { lastInterimAt = performance.now(); hudStatus('"' + heard + '"', true); },
        onFinal: (heard) => {
          const finalAt = performance.now();
          externalListening = false;
          hudLive(false);
          handleFinalTranscript(heard, [heard], texts, els, key,
            Math.round(finalAt - lastInterimAt), "vocalbridge", lastInterimAt);
        },
        onError: (error) => {
          externalListening = false;
          hudLive(false);
          hudStatus("Vocal Bridge: " + (error?.message || error?.code || "recognition error"));
        },
      });
      if (!started) externalListening = false;
    } catch (error) {
      externalListening = false;
      hudLive(false);
      hudStatus("Vocal Bridge start failed: " + (error?.message || error?.code || "unknown"));
    }
  }

  /* ── HUD ──────────────────────────────────────────────────────────────── */
  const hud = document.createElement("div");
  hud.style.cssText = "position:fixed;left:0;right:0;bottom:0;z-index:99999;background:rgba(8,6,14,.94);" +
    "color:#f2eef7;font:12px ui-monospace,Menlo,monospace;padding:8px 10px;border-top:1px solid #333;" +
    "max-height:42vh;display:flex;flex-direction:column;gap:6px";
  hud.innerHTML =
    '<div style="display:flex;gap:8px;align-items:center">' +
      '<b id="vl-status" style="flex:1;font-weight:600"></b>' +
      '<button id="vl-mic"  style="cursor:pointer">mic</button>' +
      '<button id="vl-mute" style="cursor:pointer">sound on</button>' +
      '<button id="vl-copy" style="cursor:pointer">copy log</button>' +
      '<button id="vl-min"  style="cursor:pointer">–</button>' +
    '</div>' +
    '<div id="vl-sum" style="color:#f5c451"></div>' +
    '<div id="vl-rows" style="overflow:auto;flex:1;white-space:pre;line-height:1.5"></div>';
  document.addEventListener("DOMContentLoaded", () => document.body.appendChild(hud));
  if (document.body) document.body.appendChild(hud);

  const el = (id) => document.getElementById(id);
  function hudStatus(msg, live) { const s = el("vl-status"); if (s) s.textContent = msg; hudLive(live); }
  function hudLive(on) { const b = el("vl-mic"); if (b) b.style.background = on ? "#ff6b57" : ""; }

  function record(heard, matched, m, stt, mm, total, provider) {
    log.push({ heard, matched, score: m.score, margin: m.margin, via: m.via,
      provider: provider || "vocalbridge", stt, match: mm, total });
    const rows = el("vl-rows"), sum = el("vl-sum");
    if (!rows) return;
    rows.textContent = log.map((r, i) =>
      (i + 1) + "  " + pad(r.heard, 30) + " -> " + pad(r.matched || "NO MATCH", 32) +
      " s=" + r.score + " m=" + r.margin + " " + pad(r.via, 9) + " " + pad(r.provider, 11) +
      " stt=" + r.stt + "ms match=" + r.match + "ms total=" + (r.total == null ? "-" : r.total + "ms")
    ).join("\n");
    rows.scrollTop = rows.scrollHeight;
    const tot = log.filter((r) => r.total != null).map((r) => r.total);
    const hits = log.filter((r) => r.matched && r.matched.indexOf("(unsure)") < 0).length;
    sum.textContent = tot.length
      ? "n=" + log.length + "  matched=" + hits + "/" + log.length +
        "  median=" + median(tot) + "ms  min=" + Math.min.apply(null, tot) + "  max=" + Math.max.apply(null, tot)
      : "n=" + log.length + " (no successful matches yet)";
  }
  const pad = (s, n) => String(s == null ? "" : s).slice(0, n).padEnd(n);
  const median = (a) => { const s = a.slice().sort((x, y) => x - y), i = s.length >> 1;
    return s.length % 2 ? s[i] : Math.round((s[i - 1] + s[i]) / 2); };

  // Permission prompts are most reliable when requested directly from a user
  // gesture. The game's initial click primes access before the first choice.
  document.addEventListener("click", () => { primeMicPermission(); }, { capture: true, once: true });

  document.addEventListener("click", (e) => {
    const id = e.target && e.target.id;
    if (id === "vl-mic")  { const els = choiceEls(); stopMic(); enableMicAndStart(els.map(choiceTextOf), els, choiceKey); }
    if (id === "vl-mute") { muted = !muted; if (muted) shutUp(); e.target.textContent = muted ? "muted" : "sound on"; }
    if (id === "vl-min")  { const r = el("vl-rows"), s = el("vl-sum");
      const hide = r.style.display !== "none"; r.style.display = s.style.display = hide ? "none" : ""; }
    if (id === "vl-copy") {
      const text = ["#\theard\tmatched\tscore\tmargin\tvia\tprovider\tsttMs\tmatchMs\ttotalMs"].concat(
        log.map((r, i) => [i + 1, r.heard, r.matched || "NO MATCH", r.score, r.margin, r.via, r.provider, r.stt, r.match, r.total == null ? "" : r.total].join("\t"))
      ).join("\n");
      navigator.clipboard.writeText(text).then(() => { e.target.textContent = "copied"; setTimeout(() => (e.target.textContent = "copy log"), 1200); });
    }
  });

  // Keyboard fallback: 1/2/3 picks, M opens the mic.
  document.addEventListener("keydown", (e) => {
    const els = choiceEls();
    if (e.key >= "1" && e.key <= "9" && els.length) { const i = +e.key - 1; if (els[i]) { shutUp(); clickIt(els[i]); } }
    if (e.key.toLowerCase() === "m" && els.length) { stopMic(); enableMicAndStart(els.map(choiceTextOf), els, choiceKey); }
  });

  /* ── boot ─────────────────────────────────────────────────────────────── */
  function boot() {
    const w = $(CFG.words), c = $(CFG.choices);
    if (!w || !c) return setTimeout(boot, 400);
    if (CFG.syncAdvance && window.Game) {
      window.Game.CLICK_TO_ADVANCE = true;
      const toggle = document.getElementById("text_automatic_toggle");
      if (toggle) toggle.textContent = "on click (voice-synced)";
    }
    preloadAudio();
    new MutationObserver(onWordsChanged).observe(w, { childList: true, subtree: true, characterData: true });
    new MutationObserver(onChoicesChanged).observe(c, { childList: true, subtree: true, characterData: true });
    const options = $("#options");
    if (options) new MutationObserver(onChoicesChanged).observe(options, { attributes: true, attributeFilter: ["style"] });
    const idx = window.VOICE_INDEX || {};
    const count = idx.version === 2 ? Object.keys(idx.lines || {}).length : Object.keys(idx).length;
    const recorded = Object.values((window.VOICE_AUDIO_MANIFEST || {}).lines || {}).filter((line) => line.available).length;
    const sttProvider = externalSTT ? "Vocal Bridge" : "no STT";
    hudStatus("voice layer ready - " + sttProvider + ", " + count + " lines indexed, " + recorded + " recorded");
    onWordsChanged(); onChoicesChanged();
  }
  boot();

  window.VoiceLayer = { CFG, log, match, speak, startMic, stopMic, primeMicPermission, lineFor,
    sttProvider: externalSTT ? "vocalbridge" : "none" };
})();
